dependencies:
- name: "loki"
  condition: loki.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "*"
- name: "promtail"
  condition: promtail.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "*"
- name: "fluent-bit"
  condition: fluent-bit.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "*"
- name: "kube-prometheus-stack"
  condition: kube-prometheus-stack.enabled
  version: "*"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: "grafana"
  condition: kube-prometheus-stack.grafana.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "*"
- name: "prometheus"
  condition: kube-prometheus-stack.prometheus.enabled
  version: "*"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: "filebeat"
  condition: filebeat.enabled
  version: "*"
  repository:  "https://helm.elastic.co"
- name: "logstash"
  condition: logstash.enabled
  version: "*"
  repository:  "https://helm.elastic.co"
